### ISSUE TITLE
sudo needed for running PiGpio

### ISSUE THREAD

**Issue by dobova86** [unosquare/pigpio-dotnet#10]
The PiGpio is working very nice and fast, but I can't start NetCore code as normal user ("pi"), it needs "sudo" to work. Is there a solution to this issue? I've searched around, but I coudn't solve. Is there anyone can help?

**Comment by k3z0** [comment]
Hi @dobova86 

In order to access peripherals, PiGpio performs a memory mapping from **/dev/mem** file, this way they can access peripherals as if they were programming the actual microprocessor. Nevertheless, this file can only be accessed as a root user, so you shall running it using **sudo**.

**Comment by dobova86** [comment]
> 
> 
> Hi @dobova86
> 
> In order to access peripherals, PiGpio performs a memory mapping from **/dev/mem** file, this way they can access peripherals as if they were programming the actual microprocessor. Nevertheless, this file can only be accessed as a root user, so you shall running it using **sudo**.

Thanks for reply and clarification.
