### ISSUE TITLE
sigHandler: Unhandled signal 30, terminating and sigHandler: Unhandled signal 2, terminating

### ISSUE THREAD

**Issue by RelSMayer** [unosquare/pigpio-dotnet#11]
I wrote an application on WinForm. What the program does. When pressing the touch button that is connected to BCM23, the LED lights on and off (BCM18).
I run this application with the command: `sudo mono WindowsFormsApp6.exe`
The program works for some time (about 3-5 minutes) and then freezes and writes an error:

![321312](https://user-images.githubusercontent.com/9536204/55626471-4a130100-57b4-11e9-9b8e-68c7c0ca7660.jpg)

How can this problem be solved?
Help me please.

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Unosquare.PiGpio.NativeMethods;
using Unosquare.PiGpio.NativeEnums;
using System.Threading;

namespace WindowsFormsApp6
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Setup.GpioInitialise();
            var pin23 = SystemGpio.Bcm23;
            IO.GpioSetPullUpDown(pin23, GpioPullMode.Up);
            IO.GpioSetAlertFunc(UserGpio.Bcm23, triggerLED);
        }
        
        private void triggerLED(UserGpio userGpio, LevelChange levelChange, uint timeMicrosecs)
        {
            var LED_gpio = SystemGpio.Bcm18;
            if (levelChange == 0)
            {
                IO.GpioWrite(LED_gpio, true);
            }
            else
            {
                IO.GpioWrite(LED_gpio, false);
            }
        }
    }
}
```
Previously, I deduced in the textBox1:
```
private void triggerLED(UserGpio userGpio, LevelChange levelChange, uint timeMicrosecs)
        {
            var LED_gpio = SystemGpio.Bcm18;
            if (levelChange == 0)
            {
                IO.GpioWrite(LED_gpio, true);
                textBox1.Text += " gpio=" + userGpio + " level = " + levelChange + " tick =" + timeMicrosecs + '\r' + '\n';
            }
            else
            {
                IO.GpioWrite(LED_gpio, false);
                textBox1.Text += " gpio=" + userGpio + " level = " + levelChange + " tick =" + timeMicrosecs + '\r' + '\n';
            }
        }
```
but after a couple of button presses, the application hangs with an error:
`sigHandler: Unhandled signal 30, terminating`

**Comment by mariodivece** [comment]
Some reference: http://people.cs.pitt.edu/~alanjawi/cs449/code/shell/UnixSignals.htm
Additional Note:
I have also experienced issues with Alert signals using this library. The IRQ implementation looks a little finicky...

**Comment by mariodivece** [comment]
I remember I was able to get certain level of stability by adding this to `pigpio.h`
```c
#define EMBEDDED_IN_VM
```

See: https://github.com/joan2937/pigpio/search?q=EMBEDDED_IN_VM&unscoped_q=EMBEDDED_IN_VM

**Comment by Ergonoodle** [comment]
@mariodivece, I did not understand how to apply it in my project.
I can not import into my project pigpio.h and pigpio.c.
If I will not create a dll file with the connection of these libraries and the creation of callback functions.
Sorry if I said nonsense...

**Comment by k3z0** [comment]
Hi @Ergonoodle 

Here is a copy of **libpigpio.so** compiled using the **EMBEDDED_IN_VM** directive. Copy it to your target directory and test it. 

It seems that the library is more stable compiled this way. Try to use it and let me know your results.

Greetings.

[libpigpio.zip](https://github.com/unosquare/pigpio-dotnet/files/3287648/libpigpio.zip)

**Comment by tloten** [comment]
You can call ` Setup.GpioCfgSetInternals(ConfigFlags.NoSignalHandler);` to configure pigpio with the appropriate flags. This achieves the same thing as the `EMBEDDED_IN_VM` directive mentioned earlier but doesn't require a custom build of pigpio.
You need to call the above prior to any of the unosquare stuff being initialized. Personally I bypass all the bootstrapping process and simply have my own init function that looks something like this:
``` 
public static void Initialize()
{
    Setup.GpioCfgSetInternals(ConfigFlags.NoSignalHandler);
    var result = Setup.GpioInitialise();
    Console.WriteLine($"Hardware Initialize result {result}");
}  
```

**Comment by k3z0** [comment]
Hi @tloten 

We already add the NoSignalHandler flag by default to the [source code](https://github.com/unosquare/pigpio-dotnet/blob/9ab3b735ddad208e3330c057c850c83b5c280bb9/Unosquare.PiGpio/Board.cs#L31).

**Comment by tloten** [comment]
@k3z0 Just did some digging, as it wasn't set on the latest nuget library that I'm using. It looks like it was added 5 days ago in commit 58d43d4dc :)
FYI I was running on .net core 3.0, on a Pi4B+ (previous comments appear to be running under mono & WinForms). I'm still not sure why this issue isn't more widespread - for me it was crashing consistently as soon as it wrote to i2c. Perhaps it's specific to the peripherals being used. But in any case, setting NoSignalHandler fixed it completely.
Anyway, looks like it'll be fixed in the next release, so that's great. Thanks for an excellent library!
