### ISSUE TITLE
Setup.GpioInitialise() always returns InitFailed on Raspberry PI 3B+

### ISSUE THREAD

**Issue by trancefreak77** [unosquare/pigpio-dotnet#33]
Hi,

I always get InitFailed when calling Setup.GpioInitialise. Board.LibraryVersion returns 68. The pigpio daemon is running and I can use the command pigs so I am sure pigpio is working correctly.

But the Unosquare library can't initialize the library. What can I check to find the problem?
I am running Raspbian Buster.

Thanks,
Christian

**Comment by trancefreak77** [comment]
Update: Is Mono still compatible with the current NuGet package? I'm using Mono, could this be the problem?

**Comment by jaessy77** [comment]
Hi @trancefreak77 ,
initially I had the same problems on my RPI3B+ running the new Rasbian Buster Image.. but I figured out that my mono installation together with the pigpio library was not setup correctly.
sudo apt-get update
sudo apt-get install mono-complete
sudo apt-get upgrade
After this actions it worked brilliant, also with X11-forwarding and VisualStudio 2019 Community Edition and integrated VSMonoDebugger
Kind regards
Marco

**Comment by k3z0** [comment]
Hi @jaessy77 

Thanks for your answer. I hope this can help @trancefreak77 with his problem.

**Comment by k3z0** [comment]
Hi @trancefreak77 

I just notice that you are running the Pigpio daemon, but the Unosquare's library does not support the daemon, so, you must stop running the daemon before using our library.
