### ISSUE TITLE
Program crashes when compiling with configuration = Release

### ISSUE THREAD

**Issue by erikkj** [unosquare/pigpio-dotnet#34]
When I compile with my app with `dotnet publish -r linux-arm -o dist -c Release` the app is very unstable. I get a lot of messages like this: `2019-10-30 14:11:31 sigHandler: Unhandled signal 34, terminating`

If I compile using `dotnet publish -r linux-arm -o dist -c Debug` the app is much more stable.

Is this something you are familiar with?

**Comment by k3z0** [comment]
Hi @erikkj 

I think signals are a Linux (POSIX) mechanism for one-way asynchronous notifications (messages sent by the operating system or some applications). So, in order to have a better idea about this problem, could you please tell us more details about your development environment?

- Are you compiling directly on Linux?
- Which NetCore version are you using?

Could you please share your code to run some tests?

**Comment by erikkj** [comment]
I am compiling on Windows. The project is targeting netcoreapp2.1. I compile the program as a self contained app, so NetCore is not installed on the Pi.

The compiled files are transferred to a Raspberry Pi running Rasbian Stretch Lite. The program runs as a service installed with systemctl.

One thing I have noticed is that the embedded resource is not working (libgpio.so). Therefore I have installed pigpio with `apt-get install pigpio`. 

When the application starts I initialize some pins as output, and some as input. For the input pins I register a interrupt with callback.

```
		public void Init()
		{
			lock (_lock)
			{
				if (_initialized)
				{
					return;
				}

				Pi.Init<BootstrapPiGpio>();

				foreach (var outputPin in _settings.OutputPins)
				{
					var pin = Board.Pins[(int)outputPin.Value];
					pin.PullMode = Unosquare.PiGpio.NativeEnums.GpioPullMode.Off;
					pin.Direction = Unosquare.PiGpio.NativeEnums.PinDirection.Output;
					pin.Value = _settings.InvertPins;
				}

				foreach (var inputPin in _settings.InputPins)
				{
					var pin = Board.Pins[(int)inputPin.Value];
					new GpioInterruptPiGpio(pin, 100, Unosquare.PiGpio.NativeEnums.GpioPullMode.Up, HandleInterrupt);
				}

				_initialized = true;
			}
		}
```

Here is the interrupt class:
```
	public class GpioInterruptPiGpio
	{
		private readonly Action<GpioPin, bool> _callback;
		private readonly GpioPin _gpioPin;
		private readonly uint _interruptTime;

		private ulong _lastInterruptTime;
		private bool _lastInterruptState;

		private static object _lock = new object();

		public GpioInterruptPiGpio(GpioPin gpioPin, uint interruptTime, Unosquare.PiGpio.NativeEnums.GpioPullMode pullMode, Action<GpioPin, bool> callback)
		{
			_callback = callback;
			_interruptTime = interruptTime;

			_gpioPin = gpioPin;
			_gpioPin.PullMode = pullMode;
			_gpioPin.Direction = Unosquare.PiGpio.NativeEnums.PinDirection.Input;
			_gpioPin.Interrupts.EdgeDetection = Unosquare.PiGpio.NativeEnums.EdgeDetection.EitherEdge;
			_lastInterruptState = _gpioPin.Value;
			_lastInterruptTime = Pi.Timing.Microseconds;


			_gpioPin.Interrupts.Start((pin, level, tick) =>
			{
				lock (_lock)
				{
					var time = Pi.Timing.Milliseconds;

					if (_gpioPin.Value == _lastInterruptState && interruptTime - _lastInterruptTime <= _interruptTime)
					{
						return;
					}

					_lastInterruptTime = time;
					_lastInterruptState = _gpioPin.Value;

					callback(_gpioPin, _gpioPin.Value);
				}
			});
		}
	}
```

**Comment by erikkj** [comment]
I have created project that you can test with: https://github.com/erikkj/pi-io
This program runs fine for a while on the Pi, but exits with the message: `sigHandler: Unhandled signal 34, terminating`

I think it is something that is happening in pigpio.c: https://github.com/joan2937/pigpio/blob/master/pigpio.c#L5571

There must is something I do wrong I guess, but I dont't know what to do...

**Comment by k3z0** [comment]
Hi @erikkj 

I think the problem you are facing is similar to that in the issue #11 

Could you please try using the library I mentioned in this [comment](https://github.com/unosquare/pigpio-dotnet/issues/11#issuecomment-501832540)

**Comment by erikkj** [comment]
Hi @k3z0 

Yes the problem was similar to that issue. 
I still get an unexpexted error when stopping the application. When calling `Board.Release()` I think there is something inside libpigpio.so calling `Exit(-1)`

**Comment by k3z0** [comment]
Hi @erikkj 

The problem is because of the use of Signal Handler. The library I mentioned to you earlier is compiled with the NoSignalHandler flag.

Did you be able to test it?

**Comment by erikkj** [comment]
@k3z0  yes, I tested the library, but the problem when I call board.Release is still there.

**Comment by k3z0** [comment]
I already checked the pigpio source code and there isn't any call to `exit(-1)` when `gpioTerminate` (Board.Release) is called.

Could you please share your code?
