### ISSUE TITLE
Connecting to pigpiod

### ISSUE THREAD

**Issue by ghost** [unosquare/pigpio-dotnet#40]
Could you please implement a way of using pigpiod daemon instead of using the pipe interface?
When using the managed way you offer in your library, I did not found a way to chose between the two possibilities that PiGpio is offering.

**Comment by k3z0** [comment]
Hi @Hotrunner 

As you mention, for the moment, we don't have any support for using pigpio Daemon. We are going to evaluate whether is a good option to implement this alternative in our library, but I think this wouldn't be in the short term.

Could you please give us more information about what are you doing in your app?

How are you using your app, that you need the pigpio daemon?
How implementing this solution could help you to achieve what you need?
It is not possible to achieve what you need using the regular pigpio library (without the daemon)?

**Comment by ghost** [comment]
Hello @k3z0 ,

the first and most important reason is sending commands over the network.
Another reason is, you don't need sudo. 
I think it's not possible to use the default pigpio library without sudo, right?

**Comment by k3z0** [comment]
You are right @Hotrunner, since pingpio access directly to system registers to take control over the IC, it is not possible to use it without sudo.
