### ISSUE TITLE
How to use it directly with cs file?

### ISSUE THREAD

**Issue by yuzouDE** [unosquare/pigpio-dotnet#44]
For some reasons, my monodevelop/VS Code doesn't work.

Could someone tell me, if there is still a chance to use this library and how?

Thx in advance :)

**Comment by yuzouDE** [comment]
Sry Im new for C#.

Now Im tried do it in another machine with Monodevelop.

I added package through Nuget and tried example as following:

```
using System;
using Unosquare.RaspberryIO;

namespace test
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            var pin = Board.Pins[18];

            while (true)
            {
                pin.Value = !pin.Value;
                Thread.Sleep(500);
            }
        }
    }
}
```

But Board and Thread cannot be recognized.

**Comment by geoperez** [comment]
You need to include the correct namespace like `System.Threading` for Thread class.

**Comment by k3z0** [comment]
Hi @yuzouDE 

RaspberryIO is an abstracted library, you must add an actual implementation like [WiringPi-dotnet](https://github.com/unosquare/wiringpi-dotnet/)

```
Install-Package Unosquare.WiringPi
```

You can find some examples and further help in [here](https://github.com/unosquare/raspberryio/).

**Comment by geoperez** [comment]
Can I close this issue?
