### ISSUE TITLE
Error when compiling with msbuild

### ISSUE THREAD

**Issue by yuzouDE** [unosquare/pigpio-dotnet#45]
I tried to compile the pigpio-dotnet/Unosquare.PiGpio/Unosquare.PiGpio.csproj with:
`msbuild Unosquare.PiGpio.csproj`

And then use the dll for my cs program:
`mcs motor.cs -r:Unosquare.PiGpio.dll`

However I got error with I target netcoreapp3.0:
```
error CS0012: The type `System.Enum' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

I tried to target netstandard2.0, the similar error:
```
error CS0012: The type `System.Enum' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

```

Any ideas will be appreciated :)

**Comment by yuzouDE** [comment]
I did some research. I think it may be a environment mismatching because I dont have Visual Studio installed in my Rapberry Pi. What I have is netcoreapp3.0 and .NET Framework 4.5 (instead of Framework 4.7).

But How can I use this library in my environment then?

**Comment by k3z0** [comment]
hi @yuzouDE 

Try to use [dotnet build](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build):

```
dotnet build -f netcoreapp2.0
```
