### ISSUE TITLE
Publish package to Nuget

### ISSUE THREAD

**Issue by Rainson12** [unosquare/pigpio-dotnet#5]
Would you mind publishing the package to nuget? Otherwise projects which will make use of pigpio-dotnet will always contain hard copies of the whole project which in future will make it hard to keep them up to date

**Comment by geoperez** [comment]
You can find current master branch published at:

https://www.nuget.org/packages/Unosquare.PiGpio/

**Comment by Rainson12** [comment]
awesome - thanks a lot. Im going to update
