### ISSUE TITLE
PiGpio not imlement Abstractions

### ISSUE THREAD

**Issue by wolfgangmauer** [unosquare/pigpio-dotnet#55]
There are no Interfaces used in PiGpio(IGpioController/IGpioPin/ISpiChannel/etc...)

```
public sealed class GpioPin
{
...
}
```
should be 
```
public sealed class GpioPin : IGpioPin
{
...
}
```

Maybe this is a feature request?

**Comment by geoperez** [comment]
@k3z0 can you help us validate this?
