### ISSUE TITLE
I can't install:"Unosquare.PiGpio 0.0.2".

### ISSUE THREAD

**Issue by RelSMayer** [unosquare/pigpio-dotnet#8]
I can install Unosquare.PiGpio 0.0.1. But I can not install "Unosquare.PiGpio 0.0.2".
`Error: Unable to install the “Unosquare.PiGpio 0.0.2” package. You are trying to install this package into a project, the required platform version of which is “.NETFramework, Version = v4.6.1”, but the package does not contain references to assemblies or content files compatible with this platform. Additional information can be obtained from the author of the package.`

**Comment by geoperez** [comment]
What .NET framework are you using?

**Comment by RelSMayer** [comment]
I use .NETFramework, Version = v4.6.1.
What am I doing. I created an empty Windows Forms project (.NET Framework) Version = v4.6.1.
Open Package management NuGet and finde Unosquare.PiGpio 0.0.2 and when i install, i get this error.
 
![1231](https://user-images.githubusercontent.com/9536204/53007434-ec169e00-343f-11e9-873d-cfc5df5ef43c.png)

**Comment by geoperez** [comment]
Sorry, you need to use net462 or better.

**Comment by RelSMayer** [comment]
Thank you!
