### ISSUE TITLE
WaitForExit Hangs After Use Gpio

### ISSUE THREAD

**Issue by zahasoftware** [unosquare/pigpio-dotnet#9]
**Description**
Hi When I use any gpio and then I want to get the output of a process like "cat /proc/cpuinfo | grep Serial | awk ' {print $3}'" the application hangs in WaitForExit of Process method, I've shared a project in a repo -> [https://bitbucket.org/juandrn/waitforexithangsafterusegpio/src](https://bitbucket.org/juandrn/waitforexithangsafterusegpio/src)

**To Reproduce**
- 1.- Compile project with `dotnet publish -r linux-arm -c debug` (In visual studio 2017)
- 1.1- Send proyect to raspberry
- 2.- then execute in raspberry with : `dotnet WaitForExitAfterSocketTimeout.dll`

**Expected behavior**
The application should return the serial number, the first time always is empty, but It is not the problem, the problem Is the "System.TimeoutException"

**Error**
[https://i.imgur.com/jOtJ55L.png](https://i.imgur.com/jOtJ55L.png)

**Develop Dotnet**
[https://i.imgur.com/TapdHSh.png](https://i.imgur.com/TapdHSh.png)

**Raspberry Runtime Dotnet**
[https://i.imgur.com/RKGn6WL.png](https://i.imgur.com/RKGn6WL.png)

Best regards
If you need another information please tell me
Thanks! and great project

**Comment by geoperez** [comment]
Hello, I can't open your repository.

**Comment by zahasoftware** [comment]
Sorry, I've changed the url [https://bitbucket.org/juandrn/waitforexithangsafterusegpio/src](https://bitbucket.org/juandrn/waitforexithangsafterusegpio/src)

**Comment by k3z0** [comment]
Hi @juandrn 

I was testing your code. It seems that the error is causing by the PiGpio underlying library. I don't know exactly why the error is happening, but if you just extract the library initialization out of the for cycle all works just fine:

```csharp
        static void Main(string[] args)
        {
            try
            {
                var gepioInitializeResult = Setup.GpioInitialise();
                if (gepioInitializeResult < 0)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    throw new Exception($"Fail GpioInitialise: {gepioInitializeResult.ToString()}");
                }

                for (int i = 0; i < 5; i++)//Five zombie process in linux
                {

                    Console.WriteLine($"Write GPIO Test {i}");
                    var pin = (SystemGpio)20;
                    IO.GpioSetMode(pin, PinMode.Output);
                    IO.GpioWrite(pin, i % 2 == 0);
                    Console.WriteLine(i % 2 == 0 ? "ON" : "OFF");

                    // Act
                    IOTerminal iOTerminal = new IOTerminal();
                    var result = iOTerminal.Execute(new ProcessInput
                    {
                        Command = "cat /proc/cpuinfo | grep Serial | awk ' {print $3}'",
                        ShellName = "/bin/bash",
                        Arguments = ""
                    });

                    result.StandardOutput =
                        result.StandardOutput
                        .Where(o => o?.Trim()?.Equals("") != true).ToArray(); ;

                    Console.WriteLine($"Process {i} => {  string.Join(",", result.StandardOutput) }");

                    Task.Delay(1000).Wait();
                }
            }
            catch (System.Exception nse)
            {
                Console.WriteLine(nse.ToString());
            }
            finally
            {
                Setup.GpioTerminate();
            }

            Console.Write("Press any key to exit.");
            Console.ReadKey();
        }
```

![imagen](https://user-images.githubusercontent.com/5455304/59230084-fbae2400-8ba1-11e9-8d66-742d27930497.png)
